# Generated by Django 4.2 on 2023-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='', verbose_name='Photo de profil'),
            preserve_default=False,
        ),
    ]
